apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order-container
        image: kkaggarwal/order-service:0.0.2
        ports:
        - containerPort: 8081